FROM scratch
MAINTAINER Stefan Hellkvist <hellkvist@gmail.com>

ARG REL_NAME
ARG REL_VSN=1
ARG ERTS_VSN

ENV BINDIR /erts-${ERTS_VSN}/bin
ENV BOOT /releases/${REL_VSN}/${REL_NAME}
ENV CONFIG /releases/${REL_VSN}/sys.config
ENV ARGS_FILE /releases/${REL_VSN}/vm.args
ENV EDOCKER_COOKIE edocker_default_cookie
ENV EDOCKER_NAME edocker_default_name
ENV EDOCKER_HOST 127.0.0.1

ENV TZ=GMT

ENTRYPOINT exec ${BINDIR}/edocker_erlexec

ADD .edocker.mk/linux_rel/${REL_NAME}/ /